# Toml input file
[Parfile]
  plot_var_1 = "rhds"
  plot_var_2 = "nsol"
  plot_var_3 = "diff"
  plot_var_4 = "asol"
  plot_var_5 = "rfin"
  
  gr_amrexMG_composite_solve = ".TRUE."
  gr_amrexMG_Tol = 1e-11
  gr_amrexMG_max_iter = 1000
  
  lrefine_min       = 1
  lrefine_max       = 1
  refine_var_1      = "rfin"
  
  xmin = 0.0
  xmax = 1.0
  ymin = 0.0
  ymax = 1.0
  zmin = 0.0
  zmax = 1.0
   
  plotFileIntervalStep = 1

  ignoreForcedPlot = ".TRUE."  

  xl_boundary_type = "dirichlet"
  xr_boundary_type = "dirichlet"
  yl_boundary_type = "dirichlet"
  yr_boundary_type = "dirichlet"
  zl_boundary_type = "dirichlet"
  zr_boundary_type = "dirichlet"
