# Parfile
Parfile.plot_var_1 = "rhs"
Parfile.plot_var_2 = "nsol"
Parfile.plot_var_3 = "diff"
Parfile.plot_var_4 = "asol"

Parfile.nblockx = 8
Parfile.nblocky = 8
Parfile.nblockz = 8

#    AMR refinement parameters
Parfile.lrefine_min = 1
Parfile.lrefine_max = 1
Parfile.refine_var_1 = "asol"
Parfile.refine_cutoff_1 = 0.5

Parfile.xmax = 1.0
Parfile.xmin = 0.0
Parfile.ymax = 1.0
Parfile.ymin = 0.0
Parfile.zmax = 1.0
Parfile.zmin = 0.0
Parfile.xr_boundary_type = "dirichlet"
Parfile.xl_boundary_type = "dirichlet"
Parfile.yr_boundary_type = "dirichlet"
Parfile.yl_boundary_type = "dirichlet"
Parfile.zr_boundary_type = "dirichlet"
Parfile.zl_boundary_type = "dirichlet"
